# define SSH key to use
ARG SSHPUBKEY

# Define the base image for the second stage
FROM registry.redhat.io/rhel9/rhel-bootc:9.4

ARG EXTRA_RPM_PACKAGES=''
ARG REMOVE_RPM_PACKAGES=''
RUN mv /etc/selinux /etc/selinux.tmp && \
  dnf install -y \
  cloud-init \
  pciutils \
  tmux \
  rsync \
  ${EXTRA_RPM_PACKAGES} \
  && dnf clean all \
  && mv /etc/selinux.tmp /etc/selinux \
  && ln -s ../cloud-init.target /usr/lib/systemd/system/default.target.wants # Enable cloud-init

RUN dnf remove -y \
  ${REMOVE_RPM_PACKAGES} \
  && dnf clean all


# Setup /usr/lib/containers/storage as an additional store for images.
# Remove once the base images have this set by default.
RUN grep -q /usr/lib/containers/storage /etc/containers/storage.conf || \
    sed -i -e '/additionalimage.*/a "/usr/lib/containers/storage",' \
        /etc/containers/storage.conf

# The --build-arg "SSHPUBKEY=$(cat ~/.ssh/id_rsa.pub)" option inserts your
# public key into the image, allowing root access via ssh.
RUN if [ -n "${SSHPUBKEY}" ]; then \
    set -eu; mkdir -p /usr/ssh && \
        echo 'AuthorizedKeysFile /usr/ssh/%u.keys .ssh/authorized_keys .ssh/authorized_keys2' >> /etc/ssh/sshd_config.d/30-auth-system.conf && \
	    echo ${SSHPUBKEY} > /usr/ssh/root.keys && chmod 0600 /usr/ssh/root.keys; \
fi

# Added for running as an OCI Container to prevent Overlay on Overlay issues.
VOLUME /var/lib/containers
