# Define the base image for the second stage
FROM registry.redhat.io/rhel9/rhel-bootc:9.4

ARG EXTRA_RPM_PACKAGES='pciutils tmux bootc ostree openssh-server xorg-x11-server-Xwayland xorg-x11-xauth xorg-x11-xinit xorg-x11-xinit-session firefox xorg-x11-server-Xorg mesa-dri-drivers xorg-x11-drivers xorg-x11-fonts-75dpi tigervnc-server-module gdm' # cloud-init
ARG REMOVE_RPM_PACKAGES='libsmbclient samba-client-libs samba-common-libs sssd-ad sssd-common sssd-common-pac sssd-ipa sssd-krb5 sssd-krb5-common sssd-ldap sssd-nfs-idmap udisks2 libudisks2 avahi-libs gdisk adcli sos fwupd skopeo flashrom toolbox netavark  WALinuxAgent-udev sg3_utils zstd nano ncurses'

# bsdtar nss-altfiles efi-filesystem aardvark-dns c-ares cryptsetup criu crun lvm2 lvm2-libs  containers-common  rpm-ostree fuse gmp conmon efibootmgr efivar-libs libverto ima-evm-utils passt passt-selinux'
# polkit

RUN for package in ${REMOVE_RPM_PACKAGES}; do dnf remove -y $package;done

RUN dnf autoremove -y

RUN mv /etc/selinux /etc/selinux.tmp && \
  dnf install -y \
  ${EXTRA_RPM_PACKAGES} \
  && dnf -y upgrade \
  && dnf clean all \
  && mv /etc/selinux.tmp /etc/selinux \
  && ln -s ../cloud-init.target /usr/lib/systemd/system/default.target.wants # Enable cloud-init

# Remove documentation, man pages and locales
RUN rm -Rfv /usr/share/info/ /usr/share/man/ /usr/share/doc/ /usr/share/locale/

RUN systemctl disable rhsmcertd

ADD config/gdm-custom.conf /etc/gdm/custom.conf

# Setup /usr/lib/containers/storage as an additional store for images.
# Remove once the base images have this set by default.
RUN grep -q /usr/lib/containers/storage /etc/containers/storage.conf || \
  sed -i -e '/additionalimage.*/a "/usr/lib/containers/storage",' \
  /etc/containers/storage.conf

# Added for running as an OCI Container to prevent Overlay on Overlay issues.
VOLUME /var/lib/containers
